sylius_grid:
    grids:
        sylius_admin_brand:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.brand.class%"
            sorting:
                code: asc
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                    sortable: ~
                name:
                    type: twig
                    label: sylius.ui.name
                    options:
                        template: "@SyliusAdmin/locale/grid/field/name.html.twig"
                    sortable: ~
                code:
                    type: twig
                    label: sylius.ui.code
                    sortable: ~
                    options:
                        template: "@SyliusAdmin/shared/grid/field/code.html.twig"
            filters:
                code:
                    type: string
                    label: sylius.ui.code
            actions:
                main:
                    create:
                        type: create
                bulk:
                    delete:
                        type: delete
                item:
                    delete:
                        type: delete
                    update:
                        type: update
                    show:
                        type: show
