sylius_grid:
    grids:
        sylius_admin_brand:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.brand.class%"
            sorting:
                code: asc
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                    sortable: ~
                name:
                    type: twig
                    label: sylius.ui.name
                    options:
                        template: "@SyliusAdmin/locale/grid/field/name.html.twig"
                    sortable: ~
                code:
                    type: twig
                    label: sylius.ui.code
                    sortable: ~
                    options:
                        template: "@SyliusAdmin/shared/grid/field/code.html.twig"
            filters:
                code:
                    type: string
                    label: sylius.ui.code
            actions:
                main:
                    create:
                        type: create
                bulk:
                    delete:
                        type: delete
                item:
                    delete:
                        type: delete
                    update:
                        type: update
                    show:
                        type: show
                    reject:
                        type: apply_transition
                        label: sylius.ui.reject
                        icon: "tabler:x"
                        options:
                            link:
                                route: sylius_admin_brand_reject
                                parameters:
                                    id: resource.id
                            class: btn-danger
                            transition: reject
                            graph: sylius_brand
                    approve:
                        type: apply_transition
                        label: sylius.ui.approve
                        icon: "tabler:check"
                        options:
                            link:
                                route: sylius_admin_brand_approve
                                parameters:
                                    id: resource.id
                            class: btn-primary
                            transition: approve
                            graph: sylius_brand
                    suspend:
                        type: apply_transition
                        label: sylius.ui.suspend
                        icon: "tabler:hourglass-empty"
                        options:
                            link:
                                route: sylius_admin_brand_suspend
                                parameters:
                                    id: resource.id
                            class: btn-warning
                            transition: suspend
                            graph: sylius_brand
