sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

sylius_shop_payum:
    resource: "@SyliusPayumBundle/Resources/config/routing/integrations/sylius_shop.yaml"

sylius_payment_notify:
    resource: "@SyliusPaymentBundle/Resources/config/routing/integrations/sylius.yaml"

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius_shop.controller.locale_switch::switchAction

# see https://web.dev/change-password-url/
sylius_shop_request_password_reset_token_redirect:
    path: /.well-known/change-password
    methods: [GET]
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: sylius_shop_request_password_reset_token
        permanent: false

sylius_shop_branded_products_index:
    path: /{_locale}/branded-products/{code}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product::indexAction
        _sylius:
            template: "shop/product/brandedProducts.html.twig"
            repository:
                method: findBrandedProducts
                arguments:
                    - expr:service('sylius.repository.brand').findOneByCode($code)

sylius_shop_partial_branded_products_index:
    path: /{_locale}/_partial/brands
    methods: [GET]
    defaults:
        _controller: sylius.controller.brand::indexAction
        _sylius:
            template: "shop/brand/menu.html.twig"
